ARG NODE_VERSION

FROM node:$NODE_VERSION

ENV ROOT=/app \
    HOST=0.0.0.0 \
    PORT=3000 \
    NUXT_HOST=0.0.0.0 \
    NUXT_PORT=3000

WORKDIR $ROOT

COPY lib/* /usr/local/lib/liara/

ONBUILD ARG __NODE_MIRROR=false
ONBUILD ARG __NODE_MIRRORURL
ONBUILD ARG __NODE_GITHUBMIRRORURL
ONBUILD ARG __NODE_MAPBOXMIRRORURL

ONBUILD ENV __NODE_MIRROR=${__NODE_MIRROR}
ONBUILD ENV __NODE_MIRRORURL=${__NODE_MIRRORURL}
ONBUILD ENV __NODE_GITHUBMIRRORURL=${__NODE_GITHUBMIRRORURL}
ONBUILD ENV __NODE_MAPBOXMIRRORURL=${__NODE_MAPBOXMIRRORURL}

ONBUILD COPY package*.json .npmrc* /app/

ONBUILD RUN /usr/local/lib/liara/configure.sh

ONBUILD COPY . .

ONBUILD RUN npm run --if-present build

ONBUILD ARG __NODE_TIMEZONE=Asia/Tehran
ONBUILD ENV TZ=${__NODE_TIMEZONE}
ONBUILD RUN echo '> Configuring timezone:' $TZ && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezonero

ONBUILD ARG __VOLUME_PATH
ONBUILD ENV __VOLUME_PATH=${__VOLUME_PATH}

CMD ["npm", "start"]

EXPOSE $PORT
